export const QuerySewOutDayRep = `	SELECT *, 
ROUND(IFNULL(I.PLAN_TARGET, 0)+ IFNULL(I.PLAN_TARGET_OT, 0)+IFNULL(I.PLAN_TARGET_X_OT, 0)) AS TOTAL_TARGET, 
IFNULL(I.NORMAL_OUTPUT, 0)+ IFNULL(I.OT_OUTPUT, 0)+IFNULL(I.X_OT_OUTPUT, 0) AS TOTAL_OUTPUT 
FROM (
SELECT *, 
n.NORMAL_MP*n.PLAN_WH/n.PLAN_SEW_SMV PLAN_TARGET, 
n.OT_MP*n.PLAN_WH_OT/n.PLAN_SEW_SMV PLAN_TARGET_OT, 
n.OT_X_MP*n.PLAN_WH_X_OT/n.PLAN_SEW_SMV PLAN_TARGET_X_OT
FROM (
SELECT a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, e.ID_SITELINE,  d.SITE_NAME, d.LINE_NAME, e.SHIFT,
b.ORDER_REFERENCE_PO_NO, 
a.SCHD_CAPACITY_ID, a.SCHD_DAYS_NUMBER, 
IF(SUBSTRING(:shift ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY, 
b.ORDER_NO, b.CUSTOMER_NAME, b.CUSTOMER_PROGRAM, b.PRODUCT_ITEM_CODE, 
b.ITEM_COLOR_CODE,  b.ITEM_COLOR_NAME, b.PRODUCT_ITEM_DESCRIPTION,  
CASE WHEN r.SCH_QTY = b.MO_QTY THEN 'ALL' ELSE 'PARTIAL' END AS SIZE,
FIND_SMV(g.SMV_PLAN, c.ACTUAL_SEW_SMV,c.PLAN_SEW_SMV ) PLAN_SEW_SMV,
CASE WHEN ISNULL(m.PLAN_MP) THEN e.PLAN_MP ELSE m.PLAN_MP END PLAN_MP, m.ACT_MP,
CASE WHEN ISNULL(f.PLAN_WH) THEN e.PLAN_WH ELSE f.PLAN_WH END PLAN_WH, 
m.PLAN_MP_OT, f.PLAN_WH_OT, m.PLAN_MP_X_OT, f.PLAN_WH_X_OT, 
FIND_ACT_MP(m.ACT_MP, m.PLAN_MP, e.PLAN_MP) NORMAL_MP, -- mp normal untuk menghitung target normal
FIND_ACT_MP(m.ACT_MP_OT, m.PLAN_MP_OT, NULL) OT_MP, -- mp ot untuk menghitung target overtime
FIND_ACT_MP(m.ACT_MP_X_OT, m.PLAN_MP_X_OT, NULL) OT_X_MP, -- mp  untuk menghitung target extra ovrtime
p.NORMAL_OUTPUT, p.OT_OUTPUT, p.X_OT_OUTPUT
FROM weekly_prod_sch_detail a
LEFT JOIN viewcapacity b ON a.SCHD_CAPACITY_ID = b.ID_CAPACITY 
LEFT JOIN item_smv_header c ON c.ORDER_NO = b.ORDER_NO
-- untuk aktual SMV
LEFT JOIN smv_daily_plan g ON g.SCHD_ID = a.SCHD_ID AND g.SHIFT = :shift
LEFT JOIN item_siteline d ON a.SCHD_ID_SITELINE = d.ID_SITELINE
LEFT JOIN weekly_prod_schedule r ON a.SCH_ID = r.SCH_ID
LEFT JOIN 	(
-- Manpower_detail di join dengan item siteline untunk mendapatkan line name dan shift
	SELECT a.ID_MPD, a.MP_DATE, a.ID_SITELINE, b.SITE_NAME, b.LINE_NAME, b.SHIFT, a.PLAN_WH, a.PLAN_MP, a.ACT_WH, a.ACT_MP, a.OT_WH, a.OT_MP
	FROM manpower_detail a 
	LEFT JOIN item_siteline b ON a.ID_SITELINE = b.ID_SITELINE
	WHERE a.MP_DATE = :schDate AND b.SITE_NAME = :sitename AND b.SHIFT = :shift
	ORDER by a.ID_SITELINE
) e ON e.LINE_NAME = d.LINE_NAME
-- untuk working hour dan mp_daily_detail dipakaikan kolom shift untuk mengambil data jika line mempunyai shifting
LEFT JOIN workinghour_detail f ON f.SCHD_ID = a.SCHD_ID AND f.SHIFT = :shift
LEFT JOIN (
	SELECT DISTINCT a.SCHD_ID, a.LINE_NAME, a.SHIFT, a.PLAN_MP, a.ACT_MP, a.PLAN_MP_OT, a.ACT_MP_OT, a.PLAN_MP_X_OT, a.ACT_MP_X_OT 
	FROM   mp_daily_detail a  WHERE a.SHIFT = :shift AND DATE(a.CREATE_DATE) = :schDate
	GROUP BY a.SCHD_ID, a.LINE_NAME, a.SHIFT
) m  ON m.SCHD_ID = a.SCHD_ID AND m.SHIFT = :shift
LEFT JOIN (
	 SELECT a.ENDLINE_ACT_SCHD_ID, a.ENDLINE_SCHD_DATE, a.ENDLINE_ID_SITELINE, a.NORMAL_OUTPUT, b.SHIFT, a.OT_OUTPUT, a.X_OT_OUTPUT
	 FROM qcendlineoutput a 
	 LEFT JOIN item_siteline b ON a.ENDLINE_ID_SITELINE = b.ID_SITELINE
	 WHERE a.ENDLINE_SCHD_DATE = :schDate AND b.SITE_NAME = :sitename AND b.SHIFT = :shift
) p ON a.SCHD_ID = p.ENDLINE_ACT_SCHD_ID
-- LEFT JOIN out_prod_time_view l ON l.ENDLINE_ACT_SCHD_ID = a.SCHD_ID AND l.ENDLINE_SCHD_DATE = :schDate
LEFT JOIN item_working_shift k ON k.SHIFT_ID  = :shift AND INSTR(k.SHIFT_DAYS, DAYNAME (:schDate)) > 1
--	LEFT JOIN remark_detail o ON o.SCHD_ID = a.SCHD_ID AND o.SHIFT = :shift
WHERE a.SCHD_PROD_DATE = :schDate  AND e.MP_DATE = :schDate AND d.SITE_NAME =  :sitename 
)n 
) I ORDER BY I.ID_SITELINE`;

export const getSewOutDayRepSize = `SELECT a.SCHD_PROD_DATE, b.ENDLINE_ID_SITELINE, b.ENDLINE_ACT_SCHD_ID, b.ENDLINE_PLAN_SIZE, 
SUM(b.CHECKED) CHECKED, SUM(b.GOOD) GOOD, SUM(b.RTT) RTT, SUM(b.DEFECT) DEFECT, SUM(b.REPAIRED) REPAIRED, SUM(b.BS) BS
FROM weekly_prod_sch_detail a
LEFT JOIN viewqcendcheckall b ON a.SCHD_ID = b.ENDLINE_ACT_SCHD_ID 
LEFT JOIN item_siteline c ON  b.ENDLINE_ID_SITELINE = c.ID_SITELINE
WHERE a.SCHD_PROD_DATE = :schDate AND  c.SITE_NAME = :sitename AND c.SHIFT = :shift
GROUP BY a.SCHD_PROD_DATE, b.ENDLINE_ID_SITELINE, b.ENDLINE_ACT_SCHD_ID,  b.ENDLINE_PLAN_SIZE`;

export const QrySewDayOutByPo = `SELECT h.CUSTOMER_NAME, h.CUSTOMER_DIVISION, h.ORDER_REFERENCE_PO_NO, h.ORDER_NO, h.PRODUCT_ITEM_CODE, 
h.ITEM_COLOR_CODE,  h.ITEM_COLOR_NAME, h.PRODUCT_ITEM_DESCRIPTION, h.MO_NO,
SUM(h.SCHD_QTY)  SCHD_QTY, 
IFNULL(SUM(h.PLAN_TARGET), 0)+ IFNULL(SUM(h.PLAN_TARGET_OT), 0)+IFNULL(SUM(h.PLAN_TARGET_X_OT), 0) TOTAL_TARGET,
IFNULL(sum(h.NORMAL_OUTPUT), 0)+ IFNULL(sum(h.OT_OUTPUT), 0)+IFNULL(sum(h.X_OT_OUTPUT), 0) TOTAL_OUTPUT
FROM(
	SELECT *, 
			ROUND(IFNULL(I.PLAN_TARGET, 0)+ IFNULL(I.PLAN_TARGET_OT, 0)+IFNULL(I.PLAN_TARGET_X_OT, 0)) AS TOTAL_TARGET, 
			IFNULL(I.NORMAL_OUTPUT, 0)+ IFNULL(I.OT_OUTPUT, 0)+IFNULL(I.X_OT_OUTPUT, 0) AS TOTAL_OUTPUT 
	FROM (
		SELECT *, 
			n.NORMAL_MP*n.PLAN_WH/n.PLAN_SEW_SMV PLAN_TARGET, 
			n.OT_MP*n.PLAN_WH_OT/n.PLAN_SEW_SMV PLAN_TARGET_OT, 
			n.OT_X_MP*n.PLAN_WH_X_OT/n.PLAN_SEW_SMV PLAN_TARGET_X_OT
		 FROM (
			SELECT a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, e.ID_SITELINE,  d.SITE_NAME, d.LINE_NAME, e.SHIFT,
			b.ORDER_REFERENCE_PO_NO, 
			a.SCHD_CAPACITY_ID, a.SCHD_DAYS_NUMBER, 
			IF(SUBSTRING(:shift ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY, 
			b.ORDER_NO, b.MO_NO, b.CUSTOMER_NAME, b.CUSTOMER_PROGRAM, b.CUSTOMER_DIVISION, b.PRODUCT_ITEM_CODE, 
			b.ITEM_COLOR_CODE,  b.ITEM_COLOR_NAME, b.PRODUCT_ITEM_DESCRIPTION,  
			CASE WHEN r.SCH_QTY = b.MO_QTY THEN 'ALL' ELSE 'PARTIAL' END AS SIZE,			
			FIND_SMV(g.SMV_PLAN, c.ACTUAL_SEW_SMV,c.PLAN_SEW_SMV ) PLAN_SEW_SMV,
			CASE WHEN ISNULL(m.PLAN_MP) THEN e.PLAN_MP ELSE m.PLAN_MP END PLAN_MP, m.ACT_MP,
			CASE WHEN ISNULL(f.PLAN_WH) THEN e.PLAN_WH ELSE f.PLAN_WH END PLAN_WH, 
			m.PLAN_MP_OT, f.PLAN_WH_OT, m.PLAN_MP_X_OT, f.PLAN_WH_X_OT, 
			FIND_ACT_MP(m.ACT_MP, m.PLAN_MP, e.PLAN_MP) NORMAL_MP, -- mp normal untuk menghitung target normal
			FIND_ACT_MP(m.ACT_MP_OT, m.PLAN_MP_OT, NULL) OT_MP, -- mp ot untuk menghitung target overtime
			FIND_ACT_MP(m.ACT_MP_X_OT, m.PLAN_MP_X_OT, NULL) OT_X_MP, -- mp  untuk menghitung target extra ovrtime
			p.NORMAL_OUTPUT, p.OT_OUTPUT, p.X_OT_OUTPUT
			FROM weekly_prod_sch_detail a
			LEFT JOIN viewcapacity b ON a.SCHD_CAPACITY_ID = b.ID_CAPACITY 
			LEFT JOIN item_smv_header c ON c.ORDER_NO = b.ORDER_NO
			-- untuk aktual SMV
			LEFT JOIN smv_daily_plan g ON g.SCHD_ID = a.SCHD_ID AND g.SHIFT = :shift
			LEFT JOIN item_siteline d ON a.SCHD_ID_SITELINE = d.ID_SITELINE
			LEFT JOIN weekly_prod_schedule r ON a.SCH_ID = r.SCH_ID
			LEFT JOIN 	(
			-- Manpower_detail di join dengan item siteline untunk mendapatkan line name dan shift
				SELECT a.ID_MPD, a.MP_DATE, a.ID_SITELINE, b.SITE_NAME, b.LINE_NAME, b.SHIFT, a.PLAN_WH, a.PLAN_MP, a.ACT_WH, a.ACT_MP, a.OT_WH, a.OT_MP
				FROM manpower_detail a 
				LEFT JOIN item_siteline b ON a.ID_SITELINE = b.ID_SITELINE
				WHERE a.MP_DATE = :schDate AND b.SITE_NAME = :sitename AND b.SHIFT = :shift
				ORDER by a.ID_SITELINE
			) e ON e.LINE_NAME = d.LINE_NAME
			-- untuk working hour dan mp_daily_detail dipakaikan kolom shift untuk mengambil data jika line mempunyai shifting
			LEFT JOIN workinghour_detail f ON f.SCHD_ID = a.SCHD_ID AND f.SHIFT = :shift
			LEFT JOIN (
				SELECT DISTINCT a.SCHD_ID, a.LINE_NAME, a.SHIFT, a.PLAN_MP, a.ACT_MP, a.PLAN_MP_OT, a.ACT_MP_OT, a.PLAN_MP_X_OT, a.ACT_MP_X_OT 
				FROM   mp_daily_detail a  WHERE a.SHIFT = :shift AND DATE(a.CREATE_DATE) = :schDate
				GROUP BY a.SCHD_ID, a.LINE_NAME, a.SHIFT
			) m  ON m.SCHD_ID = a.SCHD_ID AND m.SHIFT = :shift
			LEFT JOIN (
				 SELECT a.ENDLINE_ACT_SCHD_ID, a.ENDLINE_SCHD_DATE, a.ENDLINE_ID_SITELINE, a.NORMAL_OUTPUT, b.SHIFT, a.OT_OUTPUT, a.X_OT_OUTPUT
				 FROM qcendlineoutput a 
				 LEFT JOIN item_siteline b ON a.ENDLINE_ID_SITELINE = b.ID_SITELINE
				 WHERE a.ENDLINE_SCHD_DATE = :schDate AND b.SITE_NAME = :sitename AND b.SHIFT = :shift
			) p ON a.SCHD_ID = p.ENDLINE_ACT_SCHD_ID
			-- LEFT JOIN out_prod_time_view l ON l.ENDLINE_ACT_SCHD_ID = a.SCHD_ID AND l.ENDLINE_SCHD_DATE = :schDate
			LEFT JOIN item_working_shift k ON k.SHIFT_ID  = :shift AND INSTR(k.SHIFT_DAYS, DAYNAME (:schDate)) > 1
		--	LEFT JOIN remark_detail o ON o.SCHD_ID = a.SCHD_ID AND o.SHIFT = :shift
			WHERE a.SCHD_PROD_DATE = :schDate  AND e.MP_DATE = :schDate AND d.SITE_NAME =  :sitename 
		)n 
	) I ORDER BY I.ID_SITELINE
)h
GROUP BY h.CUSTOMER_NAME, h.CUSTOMER_DIVISION, h.ORDER_REFERENCE_PO_NO, h.ORDER_NO, h.PRODUCT_ITEM_CODE, 
h.ITEM_COLOR_CODE,  h.ITEM_COLOR_NAME, h.PRODUCT_ITEM_DESCRIPTION`;

export const QrySewDaySizeByPO = `SELECT 
e.CUSTOMER_NAME, e.CUSTOMER_DIVISION, e.ORDER_REFERENCE_PO_NO, e.ORDER_NO, e.PRODUCT_ITEM_CODE, 
e.ITEM_COLOR_CODE, e.MO_NO, a.ENDLINE_PLAN_SIZE, 
SUM(a.GOOD) GOOD
FROM viewqcendcheckall a
LEFT JOIN  weekly_prod_sch_detail b ON  a.ENDLINE_SCHD_DATE = :schDate AND  b.SCHD_ID = a.ENDLINE_ACT_SCHD_ID 
LEFT JOIN  viewcapacity e ON e.ID_CAPACITY = b.SCHD_CAPACITY_ID 
LEFT JOIN item_siteline c ON a.ENDLINE_ID_SITELINE = c.ID_SITELINE
WHERE a.ENDLINE_SCHD_DATE = :schDate AND  c.SITE_NAME = :sitename AND c.SHIFT = :shift
GROUP BY e.CUSTOMER_NAME, e.CUSTOMER_DIVISION, e.ORDER_REFERENCE_PO_NO, e.ORDER_NO, e.PRODUCT_ITEM_CODE, 
e.ITEM_COLOR_CODE,  e.MO_NO, a.ENDLINE_PLAN_SIZE`;
