export const QuerySewOutDayRep = `SELECT 
a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, a.ID_SITELINE,  a.SITE_NAME, f.CUS_NAME, a.LINE_NAME, a.SHIFT, 
IF(SUBSTRING(a.SHIFT ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY,
a.PLAN_SEW_SMV, a.FT_NORMAL, a.LT_NORMAL, a.FT_OT, a.LT_OT,  a.FT_X_OT, a.LT_X_OT,
a.PLAN_MP, a.PLAN_WH, a.ACT_MP, a.PLAN_TARGET, 	a.ACT_TARGET, a.PLAN_WH_X_OT,
a.PLAN_MP_OT, a.PLAN_WH_OT,  a.ACT_MP_OT, 
a.PLAN_TARGET_OT, a.ACT_TARGET_OT,
a.ACT_MP_X_OT, a.ACT_TARGET_X_OT,
ROUND(a.TOTAL_TARGET) TOTAL_TARGET,
gl.SHIFT_START_HOUR STARTH, gl.SHIFT_END_HOUR ENDH, (a.ACT_TARGET/a.PLAN_WH) TPPM_NORMAL,
a.ACT_TARGET RTT,
a.ACT_TARGET_OT RTT_OT,
a.ACT_TARGET_X_OT RTT_X_OT,
a.NORMAL_OUTPUT,  a.OT_OUTPUT, a.X_OT_OUTPUT, a.TOTAL_OUTPUT,  
a.PLAN_EH, a.PLAN_AH, a.PLAN_EH_OT, a.PLAN_AH_OT,  a.PLAN_EH_X_OT, a.PLAN_AH_X_OT,
a.ACT_WH, a.ACT_WH_OT, a.ACT_WH_X_OT, a.ACTUAL_EH, 
IFNULL(a.PLAN_AH,0) ACTUAL_AH,
a.ACTUAL_EH_OT, 
IFNULL(a.PLAN_AH_OT,0) ACTUAL_AH_OT,
-- IF(a.ACTUAL_AH_OT < PLAN_AH_OT, PLAN_AH_OT, ACTUAL_AH_OT) ACTUAL_AH_OT, 
a.ACTUAL_EH_X_OT,
IFNULL(a.PLAN_AH_X_OT,0) ACTUAL_AH_X_OT,
-- IF(a.ACTUAL_AH_X_OT < PLAN_AH_X_OT, PLAN_AH_X_OT, ACTUAL_AH_X_OT)ACTUAL_AH_X_OT,
a.EFF_NORMAL,
a.EFF_OT,
a.EFF_X_OT,
b.SCHD_DAYS_NUMBER, c.CUSTOMER_NAME,  c.ORDER_REFERENCE_PO_NO, 
c.PRODUCT_ITEM_CODE, c.ORDER_STYLE_DESCRIPTION, c.ITEM_COLOR_CODE, c.ITEM_COLOR_NAME
FROM log_daily_output a
LEFT JOIN weekly_prod_sch_detail b ON a.SCHD_ID = b.SCHD_ID 
LEFT JOIN viewcapacity c ON c.ID_CAPACITY = b.SCHD_CAPACITY_ID
LEFT JOIN (
	SELECT DISTINCT a.SITE_NAME, a.CUS_NAME, a.SHIFT
	FROM item_siteline a 
	GROUP BY a.SITE_NAME 
) f ON f.SITE_NAME = a.SITE_NAME
LEFT JOIN item_working_shift gl ON gl.SHIFT_ID = a.SHIFT AND INSTR(gl.SHIFT_DAYS, DAYNAME(:schDate)) > 1
WHERE a.SCHD_PROD_DATE =:schDate AND a.SITE_NAME = :sitename AND a.SHIFT = :shift
ORDER BY a.ID_SITELINE`;

export const getSewOutDayRepSize = `SELECT c.ENDLINE_SCHD_DATE SCHD_PROD_DATE, c.ENDLINE_ID_SITELINE,  c.ENDLINE_ACT_SCHD_ID, c.ENDLINE_PLAN_SIZE,
IFNULL(c.RFT, 0)+IFNULL(c.REPAIRED,0) GOOD
FROM(
	SELECT
		DATE(a.ENDLINE_SCHD_DATE) AS ENDLINE_SCHD_DATE,
		a.ENDLINE_ID_SITELINE,
		a.ENDLINE_ACT_SCHD_ID,
		a.ENDLINE_PLAN_SIZE,
		SUM(CASE
			WHEN a.ENDLINE_OUT_TYPE = 'RTT' AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y' THEN a.ENDLINE_OUT_QTY
			ELSE 0
		END) AS RFT,
		SUM(CASE
			WHEN a.ENDLINE_OUT_TYPE = 'DEFECT' AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y' AND a.ENDLINE_REPAIR = 'Y'
				AND DATE(a.ENDLINE_MOD_TIME) = :schDate THEN a.ENDLINE_OUT_QTY
			ELSE 0
		END) AS REPAIRED
	FROM qc_endline_output a
	LEFT JOIN item_siteline b ON b.ID_SITELINE = a.ENDLINE_ID_SITELINE
	WHERE (a.ENDLINE_OUT_TYPE = 'RTT' OR (a.ENDLINE_OUT_TYPE = 'DEFECT' AND a.ENDLINE_REPAIR = 'Y'))
		AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y'
		AND DATE(a.ENDLINE_ADD_TIME) = :schDate
		AND b.SITE_NAME = :sitename
		AND b.SHIFT = :shift
	GROUP BY DATE(a.ENDLINE_SCHD_DATE), a.ENDLINE_ID_SITELINE, a.ENDLINE_ACT_SCHD_ID, a.ENDLINE_PLAN_SIZE
) c`;

export const QrySewDayOutByPo = `SELECT h.CUSTOMER_NAME, h.CUSTOMER_DIVISION, h.ORDER_REFERENCE_PO_NO, h.ORDER_NO, h.PRODUCT_ITEM_CODE, 
h.ITEM_COLOR_CODE,  h.ITEM_COLOR_NAME, h.PRODUCT_ITEM_DESCRIPTION, h.MO_NO,
SUM(h.SCHD_QTY)  SCHD_QTY, 
ROUND((h.TOTAL_TARGET)) TOTAL_TARGET,
SUM(h.TOTAL_OUTPUT) TOTAL_OUTPUT
FROM (
SELECT 
c.CUSTOMER_NAME, c.CUSTOMER_DIVISION, c.ORDER_REFERENCE_PO_NO, c.ORDER_NO, c.PRODUCT_ITEM_CODE, 
c.ITEM_COLOR_CODE,  c.ITEM_COLOR_NAME, c.PRODUCT_ITEM_DESCRIPTION, c.MO_NO, 
IF(SUBSTRING(a.SHIFT ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY,
IFNULL(a.TOTAL_TARGET,0) TOTAL_TARGET, a.TOTAL_OUTPUT
FROM log_daily_output a
LEFT JOIN weekly_prod_sch_detail b ON a.SCHD_ID = b.SCHD_ID 
LEFT JOIN viewcapacity c ON c.ID_CAPACITY = b.SCHD_CAPACITY_ID
LEFT JOIN (
	SELECT DISTINCT a.SITE_NAME, a.CUS_NAME, a.SHIFT
	FROM item_siteline a 
	GROUP BY a.SITE_NAME 
) f ON f.SITE_NAME = a.SITE_NAME
LEFT JOIN item_working_shift gl ON gl.SHIFT_ID = a.SHIFT AND INSTR(gl.SHIFT_DAYS, DAYNAME(:schDate)) > 1
WHERE a.SCHD_PROD_DATE =:schDate AND a.SITE_NAME = :sitename AND a.SHIFT = :shift
ORDER BY a.ID_SITELINE
) h GROUP BY h.CUSTOMER_NAME, h.CUSTOMER_DIVISION, h.ORDER_REFERENCE_PO_NO, h.ORDER_NO, h.PRODUCT_ITEM_CODE, 
h.ITEM_COLOR_CODE,  h.ITEM_COLOR_NAME, h.PRODUCT_ITEM_DESCRIPTION`;

export const QrySewDaySizeByPO = `SELECT 
e.CUSTOMER_NAME, e.CUSTOMER_DIVISION, e.ORDER_REFERENCE_PO_NO, e.ORDER_NO, e.PRODUCT_ITEM_CODE, 
e.ITEM_COLOR_CODE, e.MO_NO, a.ENDLINE_PLAN_SIZE, 
IFNULL(a.RFT, 0)+IFNULL(a.REPAIRED,0) GOOD
FROM (
	SELECT
		DATE(a.ENDLINE_SCHD_DATE) AS ENDLINE_SCHD_DATE,
		a.ENDLINE_ID_SITELINE,
		a.ENDLINE_ACT_SCHD_ID,
		a.ENDLINE_PLAN_SIZE,
		SUM(CASE
			WHEN a.ENDLINE_OUT_TYPE = 'RTT' AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y' THEN a.ENDLINE_OUT_QTY
			ELSE 0
		END) AS RFT,
		SUM(CASE
			WHEN a.ENDLINE_OUT_TYPE = 'DEFECT' AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y' AND a.ENDLINE_REPAIR = 'Y'
				AND DATE(a.ENDLINE_MOD_TIME) = :schDate THEN a.ENDLINE_OUT_QTY
			ELSE 0
		END) AS REPAIRED
	FROM qc_endline_output a
	LEFT JOIN item_siteline b ON b.ID_SITELINE = a.ENDLINE_ID_SITELINE
	WHERE (a.ENDLINE_OUT_TYPE = 'RTT' OR (a.ENDLINE_OUT_TYPE = 'DEFECT' AND a.ENDLINE_REPAIR = 'Y'))
		AND IFNULL(a.ENDLINE_OUT_UNDO, 'OK') <> 'Y'
		AND DATE(a.ENDLINE_ADD_TIME) = :schDate
		AND b.SITE_NAME = :sitename
		AND b.SHIFT = :shift
	GROUP BY DATE(a.ENDLINE_SCHD_DATE), a.ENDLINE_ID_SITELINE, a.ENDLINE_ACT_SCHD_ID, a.ENDLINE_PLAN_SIZE
) a
LEFT JOIN  weekly_prod_sch_detail b ON  a.ENDLINE_SCHD_DATE = :schDate AND  b.SCHD_ID = a.ENDLINE_ACT_SCHD_ID 
LEFT JOIN  viewcapacity e ON e.ID_CAPACITY = b.SCHD_CAPACITY_ID 
LEFT JOIN item_siteline c ON a.ENDLINE_ID_SITELINE = c.ID_SITELINE
WHERE a.ENDLINE_SCHD_DATE = :schDate AND  c.SITE_NAME = :sitename AND c.SHIFT = :shift
GROUP BY e.CUSTOMER_NAME, e.CUSTOMER_DIVISION, e.ORDER_REFERENCE_PO_NO, e.ORDER_NO, e.PRODUCT_ITEM_CODE, 
e.ITEM_COLOR_CODE,  e.MO_NO, a.ENDLINE_PLAN_SIZE`;
