export const QueryWipMonitor = `SELECT N.*, 
IFNULL(N.SCH_SIZE_QTY - N.TTL_SEWING_IN, 0) AS TTL_SEWING_IN_BAL,
IFNULL(N.TTL_SEWING_IN - N.TTL_QC_QTY, 0) AS TTL_SEWING_WIP,
IFNULL(N.TTL_QC_QTY - N.TTL_SEWING_OUT, 0) AS TTL_QC_BALANCE,
IFNULL(N.TTL_SEWING_OUT - N.TTL_PACKING_IN, 0) AS TTL_SEWING_OUT_BALANCE,
CONCAT(ROUND(IFNULL(N.TTL_SEWING_IN / N.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_LOADING_PERCENTAGE,
IF(ROUND(IFNULL(N.TTL_SEWING_IN / N.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_LOADING_STATUS,
CONCAT(ROUND(IFNULL(N.TTL_QC_QTY / N.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_QC_PERCENTAGE,
IF(ROUND(IFNULL(N.TTL_QC_QTY / N.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_QC_STATUS,
CONCAT(ROUND(IFNULL(N.TTL_SEWING_OUT / N.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_SEWING_OUT_PERCENTAGE,
IF(ROUND(IFNULL(N.TTL_SEWING_OUT / N.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_SEWING_OUT_STATUS,
CONCAT(ROUND(IFNULL(N.TTL_PACKING_IN / N.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_PACKING_IN_PERCENTAGE,
IF(ROUND(IFNULL(N.TTL_PACKING_IN / N.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_PACKING_IN_STATUS
FROM (
SELECT 
    M.SCH_ID, M.ACTUAL_MONTH,
    M.PRODUCTION_MONTH, M.MANUFACTURING_SITE,
    M.SCH_SITE, M.SCH_ID_SITELINE, M.LINE_NAME, M.CUSTOMER_NAME, 
    M.SCH_CAPACITY_ID, M.ORDER_REFERENCE_PO_NO, 
    M.PRODUCT_ITEM_CODE, M.PRODUCT_ITEM_DESCRIPTION,
    M.ORDER_STYLE_DESCRIPTION, M.ITEM_COLOR_NAME, 
    M.ITEM_COLOR_CODE, M.TARGET_PCD, M.PLAN_EXFACTORY_DATE,
    M.FINAL_DELIVERY_DATE, M.SCH_START_PROD, M.SCH_FINISH_PROD, M.SCH_ORDER,
    M.NEW_TARGET_PCD, M.NEW_PLAN_EXFACTORY_DATE,  M.NEW_FINAL_DELIVERY_DATE, 
    M.SCH_QTY, M.MO_QTY, CASE WHEN M.SCH_QTY = M.MO_QTY  THEN  'ALL' ELSE 'PARTIAL' END AS SIZE_CODE,
    SUM(M.SCH_SIZE_QTY) SCH_SIZE_QTY,
    SUM(M.TTL_SEWING_IN) TTL_SEWING_IN,
    SUM(M.TTL_QC_QTY) TTL_QC_QTY,
    SUM(M.TTL_SEWING_OUT) TTL_SEWING_OUT,
    SUM(M.TTL_PACKING_IN) TTL_PACKING_IN
FROM (
        SELECT a.SCH_ID, 
        CASE WHEN ISNULL(a.SCH_START_PROD) THEN b.PRODUCTION_MONTH ELSE DATE_FORMAT(a.SCH_START_PROD,'%M/%Y') END ACTUAL_MONTH,
        b.PRODUCTION_MONTH, b.MANUFACTURING_SITE,  a.SCH_SITE, a.SCH_ID_SITELINE, c.LINE_NAME, b.CUSTOMER_NAME, 
        a.SCH_CAPACITY_ID, a.SCH_QTY, b.MO_QTY, b.ORDER_REFERENCE_PO_NO, 
        b.PRODUCT_ITEM_CODE, b.PRODUCT_ITEM_DESCRIPTION,
        b.ORDER_STYLE_DESCRIPTION, b.ITEM_COLOR_NAME, 
        b.ITEM_COLOR_CODE, b.TARGET_PCD, b.PLAN_EXFACTORY_DATE,
        b.FINAL_DELIVERY_DATE, a.SCH_START_PROD, a.SCH_FINISH_PROD, a.SCH_ORDER,
        b.NEW_TARGET_PCD, b.NEW_PLAN_EXFACTORY_DATE,  b.NEW_FINAL_DELIVERY_DATE,
        
        d.SIZE_CODE, 
          IFNULL(d.SCH_SIZE_QTY,0) AS SCH_SIZE_QTY, 
        IFNULL(e.TTL_SEWING_IN, 0) AS TTL_SEWING_IN,
        IFNULL(f.TTL_QC_QTY, 0) AS TTL_QC_QTY,
        IFNULL(g.TTL_SEWING_OUT, 0) AS TTL_SEWING_OUT,
        IFNULL(h.TTL_PACKING_IN, 0) AS TTL_PACKING_IN
        FROM weekly_prod_schedule a  
        LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY
        LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE
        LEFT JOIN weekly_sch_size d ON d.SCH_ID = a.SCH_ID
        LEFT JOIN (
        SELECT 
            A1.SCH_ID AS SCH_ID,
            A1.SCHD_ID AS SCHD_ID,
            A1.ORDER_STYLE AS ORDER_STYLE,
            A1.ORDER_SIZE AS ORDER_SIZE,
            A1.ORDER_COLOR AS ORDER_COLOR,
            SUM(A1.SEWIN_QTY) AS TTL_SEWING_IN
        FROM viewsewingscaninqty A1
        GROUP BY A1.SCH_ID, A1.ORDER_COLOR, A1.ORDER_SIZE
        ) e ON(a.SCH_ID = e.SCH_ID AND d.SIZE_CODE = e.ORDER_SIZE)
        LEFT JOIN (
        SELECT 
            A.ENDLINE_SCH_ID AS ENDLINE_SCH_ID,
            A.ENDLINE_SCHD_ID AS ENDLINE_SCHD_ID,
            A.ENDLINE_PLAN_SIZE AS ENDLINE_PLAN_SIZE,
            SUM(A.ENDLINE_OUT_QTY) AS TTL_QC_QTY
        FROM qc_endline_output A
        WHERE A.ENDLINE_OUT_UNDO IS NULL
        GROUP BY A.ENDLINE_SCH_ID, A.ENDLINE_PLAN_SIZE
        ) f ON(a.SCH_ID = f.ENDLINE_SCH_ID AND d.SIZE_CODE = f.ENDLINE_PLAN_SIZE)
        LEFT JOIN (
        SELECT 
            AA.SCH_ID AS SCH_ID,
            AA.SCHD_ID AS SCHD_ID,
            AA.ORDER_STYLE AS ORDER_STYLE,
            AA.ORDER_SIZE AS ORDER_SIZE,
            AA.ORDER_COLOR AS ORDER_COLOR,
            AA.BDL_COUNT AS BDL_COUNT,
            SUM(AA.TFR_QTY) AS TTL_SEWING_OUT
        FROM viewsewingtfrqty AA
        GROUP BY AA.SCH_ID, AA.ORDER_COLOR, AA.ORDER_SIZE
        ) g ON(a.SCH_ID = g.SCH_ID AND b.ITEM_COLOR_CODE = g.ORDER_COLOR AND d.SIZE_CODE = g.ORDER_SIZE)
        LEFT JOIN (
        SELECT 
            AA.BARCODE_SERIAL AS BARCODE_SERIAL,
            AB.ORDER_NO AS ORDER_NO,
            AB.BUYER_PO AS BUYER_PO,
            AB.MO_NO AS MO_NO,
            AB.ORDER_COLOR AS ORDER_COLOR,
            AB.ORDER_SIZE AS ORDER_SIZE,
            SUM(AB.ORDER_QTY) AS TTL_PACKING_IN,
            AA.PACKING_SCAN_BY AS PACKING_SCAN_BY,
            AA.SCHD_ID AS SCHD_ID,
            AA.SCH_ID AS SCH_ID
        FROM (scan_packing_in AA
        LEFT JOIN order_detail AB ON(AA.BARCODE_SERIAL = AB.BARCODE_SERIAL))
        GROUP BY AA.SCH_ID, AB.ORDER_COLOR, AB.ORDER_SIZE
        ) h ON(h.SCH_ID = a.SCH_ID AND h.ORDER_COLOR =  b.ITEM_COLOR_CODE AND h.ORDER_SIZE = d.SIZE_CODE)
        WHERE a.SCH_SITE = :sitename AND a.SCH_ID IN  (
        SELECT DISTINCT a.SCH_ID  FROM weekly_prod_sch_detail a WHERE a.SCHD_PROD_DATE BETWEEN :startDate AND :endDate
        ) AND (d.SCH_SIZE_QTY + IFNULL(e.TTL_SEWING_IN, 0) <> 0)  
        ORDER BY a.SCH_ID_SITELINE, a.SCH_START_PROD ASC
    ) M GROUP BY M.SCH_ID
) N ORDER BY N.SCH_ID_SITELINE`;

export const QueryWipMonitorSize = `SELECT a.SCH_ID, b.PROD_MONTH, CASE WHEN ISNULL(a.SCH_START_PROD) THEN b.PRODUCTION_MONTH ELSE DATE_FORMAT(a.SCH_START_PROD,'%M/%Y') END ACTUAL_MONTH,
b.PRODUCTION_MONTH, b.MANUFACTURING_SITE,  a.SCH_SITE, a.SCH_ID_SITELINE, c.LINE_NAME, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID,
a.SCH_QTY, b.MO_QTY, b.ORDER_REFERENCE_PO_NO, b.PRODUCT_ITEM_CODE, b.PRODUCT_ITEM_DESCRIPTION, b.ORDER_STYLE_DESCRIPTION, b.ITEM_COLOR_NAME,  b.ITEM_COLOR_CODE, b.TARGET_PCD, b.PLAN_EXFACTORY_DATE,
b.FINAL_DELIVERY_DATE, a.SCH_START_PROD, a.SCH_FINISH_PROD, a.SCH_ORDER,
b.NEW_TARGET_PCD, b.NEW_PLAN_EXFACTORY_DATE,  b.NEW_FINAL_DELIVERY_DATE,
d.SIZE_CODE, d.SCH_SIZE_QTY,
    IFNULL(e.TTL_SEWING_IN, 0) AS TTL_SEWING_IN,
    IFNULL( d.SCH_SIZE_QTY - e.TTL_SEWING_IN, 0) AS TTL_SEWING_IN_BAL,
    IFNULL(e.TTL_SEWING_IN - f.TTL_QC_QTY, 0) AS TTL_SEWING_WIP,
    IFNULL(f.TTL_QC_QTY, 0) AS TTL_QC_QTY,
    IFNULL(f.TTL_QC_QTY - g.TTL_SEWING_OUT, 0) AS TTL_QC_BALANCE,
    IFNULL(g.TTL_SEWING_OUT, 0) AS TTL_SEWING_OUT,
    IFNULL(g.TTL_SEWING_OUT - h.TTL_PACKING_IN, 0) AS TTL_SEWING_OUT_BALANCE,
    IFNULL(h.TTL_PACKING_IN, 0) AS TTL_PACKING_IN,
    CONCAT(ROUND(IFNULL(e.TTL_SEWING_IN / d.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_LOADING_PERCENTAGE,
    IF(ROUND(IFNULL(e.TTL_SEWING_IN / d.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_LOADING_STATUS,
    CONCAT(ROUND(IFNULL(f.TTL_QC_QTY / d.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_QC_PERCENTAGE,
    IF(ROUND(IFNULL(f.TTL_QC_QTY / d.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_QC_STATUS,
    CONCAT(ROUND(IFNULL(g.TTL_SEWING_OUT / d.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_SEWING_OUT_PERCENTAGE,
    IF(ROUND(IFNULL(g.TTL_SEWING_OUT / d.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_SEWING_OUT_STATUS,
    CONCAT(ROUND(IFNULL(h.TTL_PACKING_IN / d.SCH_SIZE_QTY, 0), 2) * 100, '%') AS TTL_PACKING_IN_PERCENTAGE,
    IF(ROUND(IFNULL(h.TTL_PACKING_IN / d.SCH_SIZE_QTY, 0), 2) * 100 < 100, 'OPEN', 'COMPLETE') AS TTL_PACKING_IN_STATUS
FROM weekly_prod_schedule a  
LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY
LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE
LEFT JOIN weekly_sch_size d ON d.SCH_ID = a.SCH_ID
LEFT JOIN (
SELECT 
    A1.SCH_ID AS SCH_ID,
    A1.SCHD_ID AS SCHD_ID,
    A1.ORDER_STYLE AS ORDER_STYLE,
    A1.ORDER_SIZE AS ORDER_SIZE,
    A1.ORDER_COLOR AS ORDER_COLOR,
    SUM(A1.SEWIN_QTY) AS TTL_SEWING_IN
FROM viewsewingscaninqty A1
GROUP BY A1.SCH_ID, A1.ORDER_COLOR, A1.ORDER_SIZE
) e ON(a.SCH_ID = e.SCH_ID AND d.SIZE_CODE = e.ORDER_SIZE)
LEFT JOIN (
SELECT 
    A.ENDLINE_SCH_ID AS ENDLINE_SCH_ID,
    A.ENDLINE_SCHD_ID AS ENDLINE_SCHD_ID,
    A.ENDLINE_PLAN_SIZE AS ENDLINE_PLAN_SIZE,
    SUM(A.ENDLINE_OUT_QTY) AS TTL_QC_QTY
FROM qc_endline_output A
WHERE A.ENDLINE_OUT_UNDO IS NULL
GROUP BY A.ENDLINE_SCH_ID, A.ENDLINE_PLAN_SIZE
) f ON(a.SCH_ID = f.ENDLINE_SCH_ID AND d.SIZE_CODE = f.ENDLINE_PLAN_SIZE)
LEFT JOIN (
SELECT 
    AA.SCH_ID AS SCH_ID,
    AA.SCHD_ID AS SCHD_ID,
    AA.ORDER_STYLE AS ORDER_STYLE,
    AA.ORDER_SIZE AS ORDER_SIZE,
    AA.ORDER_COLOR AS ORDER_COLOR,
    AA.BDL_COUNT AS BDL_COUNT,
    SUM(AA.TFR_QTY) AS TTL_SEWING_OUT
FROM viewsewingtfrqty AA
GROUP BY AA.SCH_ID, AA.ORDER_COLOR, AA.ORDER_SIZE
) g ON(a.SCH_ID = g.SCH_ID AND b.ITEM_COLOR_CODE = g.ORDER_COLOR AND d.SIZE_CODE = g.ORDER_SIZE)
LEFT JOIN (
SELECT 
    AA.BARCODE_SERIAL AS BARCODE_SERIAL,
    AB.ORDER_NO AS ORDER_NO,
    AB.BUYER_PO AS BUYER_PO,
    AB.MO_NO AS MO_NO,
    AB.ORDER_COLOR AS ORDER_COLOR,
    AB.ORDER_SIZE AS ORDER_SIZE,
    SUM(AB.ORDER_QTY) AS TTL_PACKING_IN,
    AA.PACKING_SCAN_BY AS PACKING_SCAN_BY,
    AA.SCHD_ID AS SCHD_ID,
    AA.SCH_ID AS SCH_ID
FROM (scan_packing_in AA
LEFT JOIN order_detail AB ON(AA.BARCODE_SERIAL = AB.BARCODE_SERIAL))
GROUP BY AA.SCH_ID, AB.ORDER_COLOR, AB.ORDER_SIZE
) h ON(h.SCH_ID = a.SCH_ID AND h.ORDER_COLOR =  b.ITEM_COLOR_CODE AND h.ORDER_SIZE = d.SIZE_CODE)
WHERE a.SCH_SITE = :sitename AND a.SCH_ID IN  (
SELECT DISTINCT a.SCH_ID  FROM weekly_prod_sch_detail a WHERE a.SCHD_PROD_DATE BETWEEN :startDate AND :endDate
) AND (d.SCH_SIZE_QTY + IFNULL(e.TTL_SEWING_IN, 0) <> 0)  
ORDER BY a.SCH_ID_SITELINE, a.SCH_START_PROD ASC`;
