###
GET http://localhost:5001/menu
###
GET http://localhost:5001/useraccess/menuview/132
###
GET http://localhost:5001/user
###
POST http://localhost:5001/useraccess/136/37
Content-Type: application/json

{
   "MENU_ID" : 3,
    "USER_ACESS_ADD" : null,
    "USER_ACESS_DELETE" : null,
    "USER_ACESS_MOD" : null,
    "USER_ACESS_PRINT" : null,
    "USER_ACESS_VIEW" : null,
    "USER_ID" : 136
}
###
GET http://localhost:5001/useraccess/menuview/135

###
POST http://localhost:5001/login
Content-Type: application/json

{
"USER_PASS": "Asd321`",
"USER_NAME": "egi"
}

###
POST http://localhost:5001/user
Content-Type: application/json

{
"USER_INISIAL": "egi",
"USER_PASS": "Asd321`",
"USER_NAME": "egi",
"USER_EMAIL": "egi@sumbiri.com",
"USER_DEP": 0,
"USER_JAB": 0,
"USER_LEVEL": "LEVEL",
"USER_AKTIF_STATUS": 1,
"USER_DELETE_STATUS": 0,
"USER_ADD_ID": "1" 
}

###
GET http://localhost:5001/planning/capacity/2022-10-00/2022-11-00

###
POST http://localhost:5001/planning/header
Content-Type: application/json

{
"SCH_SITE": "SBR_02",
"SCH_ID_SITELINE": "SLD0000020",
"SCH_CAPACITY_ID": "SBR_01.H&M.4084711338.HM34S.10210.20221204",
"SCH_QTY": "778",
"SCH_START_PROD": "2022-11-23",
"SCH_FINISH_PROD": "2022-11-23",
"SCH_DAYS_RUN": 1,
"SCH_ORDER": 2,
"SCH_ADD_ID": 1
}
###
POST http://localhost:5001/planning/daily
Content-Type: application/json

{"SCH_ID":7,"SCHD_PROD_MONTH":"2022-11-22","SCHD_PROD_DATE":"2022-11-21","SCHD_SITE":"SBR_01","SCHD_ID_SITELINE":"SLD0000001","SCHD_CAPACITY_ID":"SBR_01.C&A.7989320360519001;002 USIM: 2190348.MD2498 Pippa Bralette.128042.20221129","SCHD_HEADER_QTY":7634,"SCHD_QTY":"3","SCHD_ADD_ID":127}
###
POST http://localhost:5001/qc/endline/qr/transfer
Content-Type: application/json

{"BARCODE_SERIAL": "200000851925"}
###
PATCH  http://localhost:5001/planning/daily
Content-Type: application/json

{"SCH_ID":7,"SCHD_PROD_MONTH":"2022-11-22","SCHD_PROD_DATE":"2022-11-22","SCHD_SITE":"SBR_01","SCHD_ID_SITELINE":"SLD0000001","SCHD_CAPACITY_ID":"SBR_01.C&A.7989320360519001;002 USIM: 2190348.MD2498 Pippa Bralette.128042.20221129","SCHD_HEADER_QTY":7634,"SCHD_QTY":"3","SCHD_ADD_ID":127}

###
GET http://localhost:5001/holidays/2002
###
GET http://localhost:5001/planning/group/18
###
GET http://localhost:5001/pocapacity/detail-cap/2022-11-00/2022-11-00/SBR_02A
###
GET http://localhost:5001/pocapacity/detail-week/2022-11-00/2022-11-00/SBR_02A
###
GET http://localhost:5001/pocapacity/list-cap-buyer/2022-11-00/2022-11-00/SBR_02A
###
GET http://localhost:5001/pocapacity/list-cap-style/2022-11-00/2022-11-00/SBR_02A
###
GET http://localhost:5001/planning/planning-daily/2022-12-19/SBR_01
###
GET http://localhost:5001/planning/group-header/header/SBR_02A.VANITY%20VAIR%20BRANDS%2C%20LP.355327.2103375%2F72037.Damask%20Neutral.20221214

###
GET http://localhost:5001/sewdashboard/allsite?date=2023-07-13
###
GET http://localhost:5001/order/order-status-mo/asdadad
###
GET http://localhost:5001/sewdashboard/ytd/list-we/2023
###
GET http://localhost:5001/sewdashboard/ytd/weekly