export const QueryDailyPlann = `SELECT a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, a.SCHD_ID_SITELINE, d.SITE_NAME, d.FOREMAN, d.LINE_NAME, a.SCHD_CAPACITY_ID, a.SCHD_DAYS_NUMBER,
a.SCHD_QTY, b.ORDER_NO, b.CUSTOMER_NAME, b.CUSTOMER_PROGRAM, b.ITEM_COLOR_CODE, b.PRODUCT_ITEM_DESCRIPTION, c.PLAN_SEW_SMV, 
e.PLAN_MP, e.PLAN_WH, e.PLAN_MP*e.PLAN_WH*60/c.PLAN_SEW_SMV TARGET
FROM weekly_prod_sch_detail a
LEFT JOIN viewcapacity b ON a.SCHD_CAPACITY_ID = b.ID_CAPACITY
LEFT JOIN item_smv_header c ON c.ORDER_NO = b.ORDER_NO
LEFT JOIN item_siteline d ON a.SCHD_ID_SITELINE = d.ID_SITELINE
LEFT JOIN manpower_detail e ON e.ID_SITELINE = d.ID_SITELINE
WHERE a.SCHD_PROD_DATE = :plannDate  AND e.MP_DATE = :plannDate`;
