export const QueryDailyPlann = `SELECT *, n.PLAN_MP*n.PLAN_WH*60/n.PLAN_SEW_SMV PLAN_TARGET,
n.PLAN_MP_OT*n.PLAN_WH_OT*60/n.PLAN_SEW_SMV PLAN_TARGET_OT
 FROM (
	SELECT a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, a.SCHD_ID_SITELINE, d.SITE_NAME, b.ORDER_REFERENCE_PO_NO, d.FOREMAN, d.LINE_NAME,
	a.SCHD_CAPACITY_ID, a.SCHD_DAYS_NUMBER, a.SCHD_QTY, b.ORDER_NO, b.CUSTOMER_NAME, b.CUSTOMER_PROGRAM, b.PRODUCT_ITEM_CODE, 
	b.ITEM_COLOR_CODE, b.PRODUCT_ITEM_DESCRIPTION, c.PLAN_SEW_SMV, 
	CASE WHEN ISNULL(m.PLAN_MP) THEN e.PLAN_MP ELSE m.PLAN_MP END PLAN_MP, 
	CASE WHEN ISNULL(f.PLAN_WH) THEN e.PLAN_WH ELSE f.PLAN_WH END PLAN_WH, 
	m.PLAN_MP_OT, f.PLAN_WH_OT
	FROM weekly_prod_sch_detail a
	LEFT JOIN viewcapacity b ON a.SCHD_CAPACITY_ID = b.ID_CAPACITY 
	LEFT JOIN item_smv_header c ON c.ORDER_NO = b.ORDER_NO
	LEFT JOIN item_siteline d ON a.SCHD_ID_SITELINE = d.ID_SITELINE
	LEFT JOIN manpower_detail e ON e.ID_SITELINE = d.ID_SITELINE
	LEFT JOIN workinghour_detail f ON f.SCHD_ID = a.SCHD_ID
	LEFT JOIN mp_daily_detail m ON m.SCHD_ID = a.SCHD_ID
    WHERE a.SCHD_PROD_DATE = :plannDate  AND e.MP_DATE = :plannDate AND d.SITE_NAME = :sitename
)n `;
