//query detail capacity
export const QueryPoByCap = `SELECT a.PRODUCTION_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME,a.CUSTOMER_DIVISION, a.CUSTOMER_PROGRAM,
a.CUSTOMER_SEASON, a.ORDER_NO, a.ORDER_REFERENCE_PO_NO, a.PRODUCT_ITEM_CODE, a.PRODUCT_ITEM_DESCRIPTION, a.ORDER_STYLE_DESCRIPTION,
a.ITEM_COLOR_CODE, a.ITEM_COLOR_NAME, a.MO_NO, a.TARGET_PCD, a.PLAN_EXFACTORY_DATE, a.FINAL_DELIVERY_DATE,
a.NEW_TARGET_PCD, a.NEW_PLAN_EXFACTORY_DATE,  a.NEW_FINAL_DELIVERY_DATE, 
a.MO_QTY, a.ORDER_QTY, n.SCH_QTY, (a.ORDER_QTY-n.SCH_QTY) VAR_QTY,  n.COUNT_SITELINE, nm.MAX_LINE, a.ID_CAPACITY, a.PROD_MONTH
FROM viewcapacity a 
LEFT JOIN (
		SELECT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID, SUM(a.SCH_QTY) SCH_QTY,  COUNT(a.SCH_ID_SITELINE) COUNT_SITELINE
		FROM weekly_prod_schedule a  
		LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
		WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND  b.MANUFACTURING_SITE = :siteName
		GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID
	) n ON a.ID_CAPACITY = n.SCH_CAPACITY_ID
LEFT JOIN (
    SELECT nb.MANUFACTURING_SITE,  MAX(nb.MAX_LINE) MAX_LINE
		FROM ( 
		SELECT na.MANUFACTURING_SITE, na.CUSTOMER_NAME, COUNT(na.SCH_ID_SITELINE) MAX_LINE
		 FROM (
			SELECT DISTINCT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE, COUNT(b.CUSTOMER_NAME) COUNT_SITELINE
			FROM weekly_prod_schedule a  
			LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
			WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND  b.MANUFACTURING_SITE = :siteName
			GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE
		) na 
		GROUP BY na.MANUFACTURING_SITE, na.CUSTOMER_NAME
	)nb
) nm ON nm.MANUFACTURING_SITE = a.MANUFACTURING_SITE
WHERE a.PROD_MONTH BETWEEN :startMonth AND :endMonth AND a.MANUFACTURING_SITE LIKE :siteName
ORDER BY a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME, a.CUSTOMER_DIVISION, a.ORDER_REFERENCE_PO_NO, a.PRODUCT_ITEM_CODE, a.PLAN_EXFACTORY_DATE
`;

//query detail schedule
export const QueryGetWeekSchPo = `SELECT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID, a.SCH_ID_SITELINE, c.LINE_NAME, a.SCH_ORDER, SUM(a.SCH_QTY) SCH_QTY
FROM weekly_prod_schedule a  
LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE 
WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND  b.MANUFACTURING_SITE = :siteName
GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID,  a.SCH_ID_SITELINE`;

//query list buyer capacity by site
export const QueryGetBuyerLis = `SELECT a.PRODUCTION_MONTH, a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME,
SUM(a.MO_QTY) MO_QTY, SUM(a.ORDER_QTY) ORDER_QTY,   nm.MAX_LINE , nd.SCH_QTY
FROM viewcapacity a 
LEFT JOIN (
		SELECT a.SCH_PROD_MONTH, b.MANUFACTURING_SITE, b.CUSTOMER_NAME, SUM(a.SCH_QTY) SCH_QTY
		FROM weekly_prod_schedule a  
		LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
		WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND  b.MANUFACTURING_SITE = :siteName
		GROUP BY  a.SCH_PROD_MONTH, b.MANUFACTURING_SITE, b.CUSTOMER_NAME
)nd ON nd.CUSTOMER_NAME =  a.CUSTOMER_NAME
LEFT JOIN (
	SELECT nb.MANUFACTURING_SITE,  MAX(nb.MAX_LINE) MAX_LINE
    FROM ( 
        SELECT na.MANUFACTURING_SITE, na.CUSTOMER_NAME, COUNT(na.SCH_ID_SITELINE) MAX_LINE
        FROM (
            SELECT DISTINCT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE, COUNT(b.CUSTOMER_NAME) COUNT_SITELINE
            FROM weekly_prod_schedule a  
            LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
            WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth  AND  b.MANUFACTURING_SITE = :siteName
            GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE
        ) na 
        GROUP BY na.MANUFACTURING_SITE, na.CUSTOMER_NAME
    )nb
) nm ON nm.MANUFACTURING_SITE = a.MANUFACTURING_SITE
WHERE a.PROD_MONTH BETWEEN :startMonth AND :endMonth  AND a.MANUFACTURING_SITE = :siteName
GROUP BY a.PRODUCTION_MONTH, a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME`;

//query get distic style capacity
export const QueryGetListStyleCap = `SELECT a.PRODUCTION_MONTH, a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME, a.PRODUCT_ITEM_CODE, a.PRODUCT_ITEM_DESCRIPTION, a.ORDER_STYLE_DESCRIPTION,
SUM(a.MO_QTY) MO_QTY, SUM(a.ORDER_QTY) ORDER_QTY, nd.SCH_QTY, nm.MAX_LINE
FROM viewcapacity a 
LEFT JOIN (
		SELECT a.SCH_PROD_MONTH, b.MANUFACTURING_SITE, b.CUSTOMER_NAME, b.PRODUCT_ITEM_CODE, SUM(a.SCH_QTY) SCH_QTY
		FROM weekly_prod_schedule a  
		LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
		WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth   AND  b.MANUFACTURING_SITE = :siteName
		GROUP BY  a.SCH_PROD_MONTH, b.MANUFACTURING_SITE, b.CUSTOMER_NAME, b.PRODUCT_ITEM_CODE
)nd ON nd.PRODUCT_ITEM_CODE =  a.PRODUCT_ITEM_CODE
LEFT JOIN (
	SELECT nb.MANUFACTURING_SITE,  MAX(nb.MAX_LINE) MAX_LINE
    FROM ( 
        SELECT na.MANUFACTURING_SITE, na.CUSTOMER_NAME, COUNT(na.SCH_ID_SITELINE) MAX_LINE
        FROM (
            SELECT DISTINCT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE, COUNT(b.CUSTOMER_NAME) COUNT_SITELINE
            FROM weekly_prod_schedule a  
            LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE =  :siteName
            WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth    AND  b.MANUFACTURING_SITE =  :siteName
            GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE
        ) na 
        GROUP BY na.MANUFACTURING_SITE, na.CUSTOMER_NAME
    )nb
) nm ON nm.MANUFACTURING_SITE = a.MANUFACTURING_SITE
WHERE a.PROD_MONTH  BETWEEN :startMonth AND :endMonth   AND  a.MANUFACTURING_SITE LIKE :siteName
GROUP BY a.PRODUCTION_MONTH, a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME, a.PRODUCT_ITEM_CODE, a.PRODUCT_ITEM_DESCRIPTION, a.ORDER_STYLE_DESCRIPTION`;

// update per Grouping per style
export const QueryListlineByStylePo = `SELECT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, b.PRODUCT_ITEM_CODE, a.SCH_ID_SITELINE, a.SCH_SITE, c.LINE_NAME, a.SCH_ORDER
FROM weekly_prod_schedule a  
LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE 
WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND b.MANUFACTURING_SITE = :siteName
GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME,  a.SCH_ID_SITELINE, b.PRODUCT_ITEM_CODE`;

// export const QueryListlineByStylePo = `SELECT b.MANUFACTURING_SITE, b.CUSTOMER_NAME, a.SCH_ID_SITELINE, a.SCH_SITE, c.LINE_NAME, a.SCH_ORDER
// FROM weekly_prod_schedule a
// LEFT JOIN viewcapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY AND b.MANUFACTURING_SITE = :siteName
// LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE
// WHERE a.SCH_PROD_MONTH BETWEEN :startMonth AND :endMonth AND b.MANUFACTURING_SITE = :siteName
// GROUP BY b.MANUFACTURING_SITE, b.CUSTOMER_NAME,  a.SCH_ID_SITELINE`;
