import { DataTypes } from "sequelize";
import db from "../../config/database.js";

export const QueryCapacity = `SELECT a.PRODUCTION_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME,a.CUSTOMER_DIVISION, a.CUSTOMER_PROGRAM,
a.CUSTOMER_SEASON, a.ORDER_NO, a.ORDER_REFERENCE_PO_NO, a.PRODUCT_ITEM_CODE, a.PRODUCT_ITEM_DESCRIPTION, a.ORDER_STYLE_DESCRIPTION,
a.ITEM_COLOR_CODE, a.ITEM_COLOR_NAME, a.MO_NO, a.TARGET_PCD, a.PLAN_EXFACTORY_DATE, a.FINAL_DELIVERY_DATE, a.MO_QTY, a.ORDER_QTY, 
n.SCH_QTY, (a.ORDER_QTY-n.SCH_QTY) VAR_QTY,
a.ID_CAPACITY
FROM ViewCapacity a 
LEFT JOIN (
	SELECT a.SCH_CAPACITY_ID, SUM(a.SCH_QTY) SCH_QTY
	FROM weekly_prod_schedule a  
	WHERE a.SCH_START_PROD >= :startDate  AND a.SCH_FINISH_PROD <= :endDate
	GROUP BY a.SCH_CAPACITY_ID
	) n ON a.ID_CAPACITY = n.SCH_CAPACITY_ID
WHERE a.PROD_MONTH BETWEEN :startMonth AND :endMonth
ORDER BY a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME, a.CUSTOMER_DIVISION, a.ORDER_REFERENCE_PO_NO, a.PRODUCT_ITEM_CODE, a.PLAN_EXFACTORY_DATE`;
// export const QueryCapacity = `SELECT * FROM ViewCapacity a WHERE a.PROD_MONTH BETWEEN :startMonth AND :endMonth
// ORDER BY a.PROD_MONTH, a.MANUFACTURING_SITE, a.CUSTOMER_NAME, a.CUSTOMER_DIVISION, a.ORDER_REFERENCE_PO_NO, a.PRODUCT_ITEM_CODE, a.PLAN_EXFACTORY_DATE`;

export const QueryGetHeadWeekSch = `SELECT b.PRODUCTION_MONTH,  a.SCH_SITE, a.SCH_ID_SITELINE, c.LINE_NAME, b.CUSTOMER_NAME, a.SCH_CAPACITY_ID,
a.SCH_QTY, b.ORDER_REFERENCE_PO_NO, b.PRODUCT_ITEM_CODE,  a.SCH_SIZE, b.PRODUCT_ITEM_DESCRIPTION, b.ORDER_STYLE_DESCRIPTION, b.ITEM_COLOR_NAME, b.TARGET_PCD, b.PLAN_EXFACTORY_DATE,
b.FINAL_DELIVERY_DATE, a.SCH_START_PROD, a.SCH_FINISH_PROD
FROM weekly_prod_schedule a  
LEFT JOIN ViewCapacity b ON a.SCH_CAPACITY_ID = b.ID_CAPACITY
LEFT JOIN item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE
WHERE a.SCH_START_PROD >= :startDate  AND a.SCH_FINISH_PROD <= :endDate`;

export const QueryGetDayliSch = `SELECT * FROM weekly_prod_sch_detail a
WHERE a.SCHD_PROD_DATE BETWEEN :startDate AND :endDate`;
