export const QueryWeekRep = (params) => {
  if (!params) return false;

  return `SELECT n.SCHD_ID, n.SCH_ID, n.SCHD_PROD_DATE, n.ID_SITELINE,  n.SITE_NAME, n.CUS_NAME, n.LINE_NAME, n.ACT_MP,
  n.CUS_LINE_NAME,
  n.SHIFT,
  n.CUSTOMER_NAME, n.ORDER_REFERENCE_PO_NO, n.PRODUCT_ITEM_CODE, n.ORDER_STYLE_DESCRIPTION, 
  n.ITEM_COLOR_CODE, n.ITEM_COLOR_NAME, n.SCHD_QTY,
  n.ACT_TARGET,
  n.ACT_TARGET_OT,
  n.ACT_TARGET_X_OT,
  n.NORMAL_OUTPUT,
  n.OT_OUTPUT,
  n.X_OT_OUTPUT,
  n.TOTAL_TARGET, 
  n.TOTAL_OUTPUT,
  IFNULL(n.ACTUAL_EH,0) ACTUAL_EH,
  IFNULL(n.ACTUAL_EH_OT,0) ACTUAL_EH_OT,
  IFNULL(n.ACTUAL_EH_X_OT,0) ACTUAL_EH_X_OT,
  IFNULL(n.ACTUAL_AH,0) ACTUAL_AH,
  IFNULL(n.ACTUAL_AH_OT,0) ACTUAL_AH_OT,
  IFNULL(n.ACTUAL_AH_X_OT,0) ACTUAL_AH_X_OT,
  IFNULL(n.ACTUAL_EH,0)+IFNULL(n.ACTUAL_EH_OT,0)+IFNULL(n.ACTUAL_EH_X_OT,0) TOTAL_EH,
  IFNULL(n.ACTUAL_AH,0)+IFNULL(n.ACTUAL_AH_OT,0)+IFNULL(n.ACTUAL_AH_X_OT,0) TOTAL_AH
  FROM (
      SELECT 
      a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, a.ID_SITELINE,  a.SITE_NAME, b.CUS_NAME, a.LINE_NAME, 
      CASE WHEN a.SHIFT = 'Shift_B' THEN CONCAT(b.CUS_NAME,' ','L-',SUBSTRING(a.LINE_NAME ,6,7),'B') ELSE 
      CONCAT(b.CUS_NAME,' ','L-',SUBSTRING(a.LINE_NAME ,6,7)) END AS CUS_LINE_NAME,
      a.SHIFT, 
      IF(SUBSTRING(a.SHIFT ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY,
      a.PLAN_SEW_SMV, a.ACT_MP, a.PLAN_WH, 
      a.ACT_TARGET,
      a.ACT_TARGET_OT,
      a.ACT_TARGET_X_OT,
      a.NORMAL_OUTPUT,
      a.OT_OUTPUT,
      a.X_OT_OUTPUT,
      a.TOTAL_TARGET, 
      a.TOTAL_OUTPUT, 
      a.ACTUAL_EH, 
      a.ACTUAL_EH_OT,
      a.ACTUAL_EH_X_OT,
      a.PLAN_AH ACTUAL_AH,
      IF(a.ACTUAL_AH_OT < PLAN_AH_OT, PLAN_AH_OT, ACTUAL_AH_OT) ACTUAL_AH_OT, 
      IF(a.ACTUAL_AH_X_OT < PLAN_AH_X_OT, PLAN_AH_X_OT, ACTUAL_AH_X_OT) ACTUAL_AH_X_OT,
      a.CUSTOMER_NAME, a.ORDER_REFERENCE_PO_NO, 
      a.PRODUCT_ITEM_CODE, a.ORDER_STYLE_DESCRIPTION, a.ITEM_COLOR_CODE, a.ITEM_COLOR_NAME, a.PRODUCTION_MONTH
      FROM log_daily_output a
      LEFT JOIN item_siteline b ON a.ID_SITELINE = b.ID_SITELINE
      WHERE  (a.TOTAL_TARGET <> '0.0' OR IFNULL(a.TOTAL_TARGET, '0.0') <> '0.0') AND (a.ORDER_REFERENCE_PO_NO IS NOT NULL)
      AND  ${params}
      -- a.SCHD_PROD_DATE BETWEEN '2023-01-01' AND  '2023-09-22'
      -- AND a.SITE_NAME = 'SBR_02A'-- AND a.SHIFT = :shift
      ORDER BY a.ID_SITELINE
) n`;
};

export const QueryMonthRep = (params) => {
  if (!params) return false;

  return `SELECT n.SCHD_ID, n.SCH_ID, DATE_FORMAT(n.SCHD_PROD_DATE, '%m-%Y') MONTH, DATE_FORMAT(n.SCHD_PROD_DATE, '%M/%Y') PRODUCTION_MONTH, n.SCHD_PROD_DATE,
  n.ID_SITELINE,  n.SITE_NAME, n.CUS_NAME, n.LINE_NAME, n.ACT_MP,
  n.CUS_LINE_NAME,
  n.SHIFT,
  n.CUSTOMER_NAME, n.ORDER_REFERENCE_PO_NO, n.PRODUCT_ITEM_CODE, n.ORDER_STYLE_DESCRIPTION, 
  n.ITEM_COLOR_CODE, n.ITEM_COLOR_NAME, n.SCHD_QTY,
  n.ACT_TARGET,
  n.ACT_TARGET_OT,
  n.ACT_TARGET_X_OT,
  n.NORMAL_OUTPUT,
  n.OT_OUTPUT,
  n.X_OT_OUTPUT,
  n.TOTAL_TARGET, 
  n.TOTAL_OUTPUT,
  IFNULL(n.ACTUAL_EH,0) ACTUAL_EH,
  IFNULL(n.ACTUAL_EH_OT,0) ACTUAL_EH_OT,
  IFNULL(n.ACTUAL_EH_X_OT,0) ACTUAL_EH_X_OT,
  IFNULL(n.ACTUAL_AH,0) ACTUAL_AH,
  IFNULL(n.ACTUAL_AH_OT,0) ACTUAL_AH_OT,
  IFNULL(n.ACTUAL_AH_X_OT,0) ACTUAL_AH_X_OT,
  IFNULL(n.ACTUAL_EH,0)+IFNULL(n.ACTUAL_EH_OT,0)+IFNULL(n.ACTUAL_EH_X_OT,0) TOTAL_EH,
  IFNULL(n.ACTUAL_AH,0)+IFNULL(n.ACTUAL_AH_OT,0)+IFNULL(n.ACTUAL_AH_X_OT,0) TOTAL_AH
  FROM (
      SELECT 
      a.SCHD_ID, a.SCH_ID, a.SCHD_PROD_DATE, a.ID_SITELINE,  a.SITE_NAME, b.CUS_NAME, a.LINE_NAME, 
      CASE WHEN a.SHIFT = 'Shift_B' THEN CONCAT(b.CUS_NAME,' ','L-',SUBSTRING(a.LINE_NAME ,6,7),'B') ELSE 
      CONCAT(b.CUS_NAME,' ','L-',SUBSTRING(a.LINE_NAME ,6,7)) END AS CUS_LINE_NAME,
      a.SHIFT, 
      IF(SUBSTRING(a.SHIFT ,1,5) = 'Shift', CAST(ROUND(a.SCHD_QTY/2) AS INT), a.SCHD_QTY ) SCHD_QTY,
      a.PLAN_SEW_SMV, a.ACT_MP, a.PLAN_WH, 
      a.ACT_TARGET,
      a.ACT_TARGET_OT,
      a.ACT_TARGET_X_OT,
      a.NORMAL_OUTPUT,
      a.OT_OUTPUT,
      a.X_OT_OUTPUT,
      a.TOTAL_TARGET, 
      a.TOTAL_OUTPUT, 
      a.ACTUAL_EH, 
      a.ACTUAL_EH_OT,
      a.ACTUAL_EH_X_OT,
      a.PLAN_AH ACTUAL_AH,
      IF(a.ACTUAL_AH_OT < PLAN_AH_OT, PLAN_AH_OT, ACTUAL_AH_OT) ACTUAL_AH_OT, 
      IF(a.ACTUAL_AH_X_OT < PLAN_AH_X_OT, PLAN_AH_X_OT, ACTUAL_AH_X_OT) ACTUAL_AH_X_OT,
      a.CUSTOMER_NAME, a.ORDER_REFERENCE_PO_NO, 
      a.PRODUCT_ITEM_CODE, a.ORDER_STYLE_DESCRIPTION, a.ITEM_COLOR_CODE, a.ITEM_COLOR_NAME, a.PRODUCTION_MONTH
      FROM log_daily_output a
      LEFT JOIN item_siteline b ON a.ID_SITELINE = b.ID_SITELINE
      WHERE  (a.TOTAL_TARGET <> '0.0' OR IFNULL(a.TOTAL_TARGET, '0.0') <> '0.0') AND (a.ORDER_REFERENCE_PO_NO IS NOT NULL)
      AND  ${params}
      -- a.SCHD_PROD_DATE =  MONTH('2023-01-01')
      -- AND a.SITE_NAME = 'SBR_02A'-- AND a.SHIFT = :shift
      ORDER BY a.ID_SITELINE
) n`;
};
